version: "3.3"

services:
  web:
    build: app/.
    restart: always
    ports:
      - "80:5000"
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - /root/rahul/redis:/app
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  mysqldb: